messages:
  pressSpace: "Press and hold space to speak"
  loadingModel: "Loading..."
  noAudioInput: "Error: No sound input!"

whisperRecognition:
  modelPath: "whisper/base.en.pt"
  lang: "en"

picoVoice:
  keywordPath: "config/Hey-Labs_en_mac_v3_0_0.ppn"
  
ollama:
  url: "http://localhost:11434/api/generate"
  model: "llava"
  # model: "bakllava"

gemini:
  model: "gemini-pro-vision"

conversation:
  greeting: "Hi, how can I help you?"
